version: "3.8"

services:
  db:
    image: postgres:12.5-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${RECIPY_DATABASE_NAME}
      - POSTGRES_USER=${RECIPY_DATABASE_USER}
      - POSTGRES_PASSWORD=${RECIPY_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  postgres_data:
